# Makefile for Raspberry Pi Drivers (if any)

# KERNEL_DIR ?= /lib/modules/$(shell uname -r)/build

# obj-m += your_driver.o

# all:
# 	make -C $(KERNEL_DIR) M=$(PWD) modules

# clean:
# 	make -C $(KERNEL_DIR) M=$(PWD) clean
